image: node:12.18.4
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@10.2.0
    - npm install
    - ng build --prod --base-href /app/
    - mkdir -p public
    - mv dist/app/* public/
  artifacts:
    paths:
      - public