image: node

pages:
  tags:
    - docker
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - rm -rf public
    - cp dist/doggo-smash/index.html dist/doggo-smash/404.html
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - main
    